---
name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action-testing:
    name: Action Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout Testing Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kustomize-everything/test-deploy
          ref: main
          path: test-deploy-reset
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset testing repo to known state
        shell: bash
        run: |-
          cd test-deploy-reset
          BRANCH="pr/${GITHUB_SHA}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -B ${BRANCH}
          git reset --hard 2c6d7862c78d9c2bd01f787a02829b5f2bf8e896
          git push origin ${BRANCH} -f

      - name: Read in examples to github output
        id: read-examples
        shell: bash
        run: |-
          # Generate unique EOF value to prevent injection attack
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          echo "SIMPLE_PROMOTION<<$EOF" >> $GITHUB_ENV
          cat example/simple-promotion.json >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

          echo "COMPLEX_PROMOTION<<$EOF" >> $GITHUB_ENV
          cat example/complex-promotion.json >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

          echo "CROSS_OVERLAY_PROMOTION<<$EOF" >> $GITHUB_ENV
          cat example/cross-overlay-promotion.json >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Checkout Testing Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kustomize-everything/test-deploy
          ref: main
          path: test-deploy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Action Test with Simple Promotion
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: ${{ env.SIMPLE_PROMOTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Show Git Diff and Reset
        shell: bash
        working-directory: test-deploy
        run: |-
          git diff
          git reset --hard

      - name: Action Test with Simple Promotion (Inline)
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: |-
            [
              {
                "name": "nginx",
                "newName": "nginx-inline",
                "newTag": "1.9999.0",
                "overlays": ["env/dev"]
              }
            ]
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Show Git Diff and Reset
        shell: bash
        working-directory: test-deploy
        run: |-
          git diff
          git reset --hard

      - name: Action Test with Complex Promotion
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: ${{ env.COMPLEX_PROMOTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Show Git Diff and Reset
        shell: bash
        working-directory: test-deploy
        run: |-
          git diff
          git reset --hard

      - name: Action Test with Cross Overlay Promotion
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: ${{ env.CROSS_OVERLAY_PROMOTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        working-directory: src
        run: |-
          pip install -r requirements.txt
          poetry install

      - name: Run Tests
        working-directory: src
        run: |-
          poetry run python -m unittest tests/*_test.py
