---
name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup:
    name: Test Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout Testing Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kustomize-everything/test-deploy
          ref: main
          path: test-deploy-reset
          ssh-key: ${{ secrets.TESTING_DEPLOY_KEY }}

      - name: Reset testing repo to known state
        shell: bash
        run: |-
          cd test-deploy-reset
          BRANCH="pr/${GITHUB_SHA}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -B ${BRANCH}
          git reset --hard 2c6d7862c78d9c2bd01f787a02829b5f2bf8e896
          git push origin ${BRANCH} -f

      - name: Read in examples to github output
        id: read-examples
        shell: bash
        run: |-
          # Set the simple-promotion output to the contents of
          # example/simple-promotion.json
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "SIMPLE_PROMOTION<<$EOF" >> $GITHUB_ENV
          cat example/simple-promotion.json >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Action Test with Simple Deployment
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: ${{ env.SIMPLE_PROMOTION }}
          ssh-key: ${{ secrets.TESTING_DEPLOY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Show Git Diff and Reset
        shell: bash
        working-directory: test-deploy
        run: |-
          git diff
          git reset --hard

      - name: Action Test with Simple Deployment
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          working-directory: test-deploy
          images: |-
            [
              {
                "name": "nginx",
                "newName": "nginx-inline",
                "newTag": "1.9999.0",
                "overlays": ["env/dev"]
              }
            ]
          ssh-key: ${{ secrets.TESTING_DEPLOY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
