name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup:
    name: Test Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout Testing Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: kustomize-everything/test-deploy
          ref: main
          path: test-deploy-reset
          ssh-key: ${{ secrets.TESTING_DEPLOY_KEY }}

      - name: Delete env/dev if it exists
        shell: bash
        run: |
          cd test-deploy-reset
          set +e
          if git ls-remote --exit-code --heads origin; then
            git push --delete origin env/dev
          fi
          set -e

      - name: Reset testing repo to known state
        shell: bash
        run: |-
          cd test-deploy-reset
          BRANCH="pr/${GITHUB_SHA}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -B ${BRANCH}
          git reset --hard 2c6d7862c78d9c2bd01f787a02829b5f2bf8e896
          git push origin ${BRANCH} -f

      - name: Action Test with Defaults
        uses: ./
        with:
          target-repo: kustomize-everything/test-deploy
          target-branch: ${{ env.BRANCH }}
          target-dir: env/dev
          working-directory: test-deploy
          image-name-tag: nginx:1.23.0
          ssh-key: ${{ secrets.TESTING_DEPLOY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
